package chat.realtime.app.Component;

import chat.realtime.app.Component.Event.PublicEvent;
import chat.realtime.app.Main.Model.Model_Send_Message;
import chat.realtime.app.Main.Model.Model_User_Account;
import chat.realtime.app.Service.Service;
import chat.realtime.app.Swing.JIMSendTextPane;
import chat.realtime.app.Swing.ScrollBar;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Nahue
 */
public class ChatBottom extends javax.swing.JPanel {

    private Model_User_Account user;

    //getters and setters
    public Model_User_Account getUser() {
        return user;
    }

    public void setUser(Model_User_Account user) {
        this.user = user;
    }

    public ChatBottom() {
        initComponents();
        init();
    }

    private void init() {
        mig = new MigLayout("fillx, filly", "0[fill]0[]2", "2[fill]2[]0");
        setLayout(mig);
        JScrollPane scroll = new JScrollPane();
        scroll.setBorder(null);
        JIMSendTextPane txt = new JIMSendTextPane();
        //update heigth textfield 
        txt.addKeyListener(new KeyAdapter() {
            @Override
            //this metod is autogenerated
            public void keyTyped(KeyEvent e) {

                refresh();
                if (e.getKeyChar() == 10 && e.isControlDown()) {
                    // User Press Control (ctrl) + enter
                    eventSend(txt);
                }
            }

        });
        txt.setBorder(new EmptyBorder(5, 5, 5, 5));
        scroll.setViewportView(txt);
        //Scroll bar from text field
        ScrollBar sb = new ScrollBar();
        sb.setBackground(new Color(229, 229, 229));
        sb.setPreferredSize(new Dimension(2, 10));
        scroll.setVerticalScrollBar(sb);

        add(sb);
        add(scroll, "w 100%");
        //create panel for buttom
        JPanel panel = new JPanel();
        panel.setLayout(new MigLayout("filly", "0[]3[]0", "0[bottom]0"));
        panel.setPreferredSize(new Dimension(30, 28));
        panel.setBackground(Color.WHITE);
        //create button send message
        JButton btn = new JButton();
        btn.setBorder(null);
        btn.setContentAreaFilled(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setIcon(new ImageIcon(getClass().getResource("/chat/realtime/app/Icon/send.png")));
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eventSend(txt);
            }
        });
        txt.setHintText("Write Message Here ...");

//create button send Emogi
        JButton btnMore = new JButton();
        btnMore.setBorder(null);
        btnMore.setContentAreaFilled(false);
        btnMore.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMore.setIcon(new ImageIcon(getClass().getResource("/chat/realtime/app/Icon/more_disable.png")));
        btnMore.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (panelMore.isVisible()) {
                    btnMore.setIcon(new ImageIcon(getClass().getResource("/chat/realtime/app/Icon/more_disable.png")));
                    panelMore.setVisible(false);
                    mig.setComponentConstraints(panelMore, "dock south, h 0!");
                    revalidate();
                } else {
                    btnMore.setIcon(new ImageIcon(getClass().getResource("/chat/realtime/app/Icon/more.png")));
                    panelMore.setVisible(true);
                    mig.setComponentConstraints(panelMore, "dock south, h 170!");
                    revalidate();
                }
            }
        });

        panel.add(btnMore);
        panel.add(btn);
  

    add(panel, 
    "wrap");
        panelMore  = new PanelMore();

    panelMore.setVisible (

    false);
    add(panelMore, 

"dock south, h 0!"); //h !0 set heigth 0

    }
    
    private void eventSend(JIMSendTextPane txt) {
        String text = txt.getText().trim();
        if (!text.equals("")) {
            //add chat item
            Model_Send_Message message = new Model_Send_Message(Service.getInstance().getUser().getId(), user.getId(), text);
            send(message);
            PublicEvent.getInstance().getEventChat().sendMessage(message);
            txt.setText("");
            txt.grabFocus();
            refresh();

        } else {
            txt.grabFocus();
        }
    }

    private void send(Model_Send_Message data) {
        Service.getInstance().getClient().emit("send_to_user", data.toJSONObject());
    }

    private void refresh() {
        revalidate();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
//Chat Emoji
    private MigLayout mig;
    private PanelMore panelMore;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
